name: ONPE Monitor

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch: # permite correrlo manualmente también

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Correr monitor
        env:
          TELEGRAM_USER: ${{ secrets.TELEGRAM_USER }}
        run: bun api/monitor.ts
